services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    working_dir: /app
    ports:
      - "3001:3001"
    command: npm run dev
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    ports:
      - "5173:5173"
    command: npm run dev
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
